Allow to compile with openssl 1.0.1
Motivation:

After upgrading the gcc version of the CI the build failed with:

[07:48:57][io.netty:netty-tcnative] [INFO] src/sslcontext.c: In function 'cert_requested':
[07:48:57][io.netty:netty-tcnative] [INFO] src/sslcontext.c:1438:13: error: implicit declaration of function 'SSL_add0_chain_cert' [-Werror=implicit-function-declaration]
[07:48:57][io.netty:netty-tcnative] [INFO]          if (SSL_add0_chain_cert(ssl, sk_X509_value(chain, i)) <= 0) {

This is due a missing ifdef condition for openssl < 1.0.2.

Modifications:

Fix ifdef

Result:

Be able to compile against openssl 1.0.1 again with newer gcc versions.