[#36] Enforce usage maven 3.1.1+
Motivation:

When using maven < 3.1 you see the follow exception:

Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/RepositorySystemSession

Modifications:

Enforce using maven 3.1.1+ so the user not get the "cryptic" exception

Result:

Better expierence for developers that try to build netty-tcnative.